### ISSUE TITLE
How to contribution?

### ISSUE THREAD

**Issue by dorosch** [PeARSearch/documents#2]
Hello, I'm sorry to write here, but I have not found other contacts for communication.

I would like to say that me and my friend from the university is very impressed with your project and we would like to find out how to help him.

Thank you so much :)

**Comment by stultus** [comment]
Hello @dorosch , 
Thank you for your interest in PeARS. 
First step is to pull the code and make it running in your local machine. once you have that in hand, you'll understand the current state of the project.  Also we will be available in the #pears irc channel in freenode. Feel free to drop in and say hi :)

**Comment by dorosch** [comment]
Oh, thank you very much)
I think you would be more convenient to answer such questions in the e-mail project.

**Comment by minimalparts** [comment]
Hi @dorosch! Thanks for your interest in the project :-) And sorry it isn't clear from our webpage how to start contributing. We should add some specific instructions there :-)

I just wanted to add to @stultus's comment that you should clone the development branch of the project, which is much more advanced than the master branch. Also, I changed the readme in there only fairly recently, and it is possible that things are missing. Just let us know here or on IRC if anything is unclear. Once you've tried things out, we can see where you might want to contribute.

Thanks a lot for getting in touch :-)
